# Generated by Django 5.2.17 on 2026-08-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KnowledgeCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("mn", "Mongolian"),
                            ("ja", "Japanese"),
                            ("ru", "Russian"),
                        ],
                        max_length=2,
                    ),
                ),
                ("transcript", models.TextField()),
                (
                    "source_media",
                    models.FileField(blank=True, null=True, upload_to="cards/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
