# Generated by Django 5.2.17 on 2026-08-29 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_knowledgecard_key_points_knowledgecard_summary_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgecard',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Who uploaded this clip. Null for anonymous/legacy uploads.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to=settings.AUTH_USER_MODEL),
        ),
    ]
